(() => {
  'use strict';
  const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d');
  const ui={level:byId('levelLabel'),score:byId('scoreLabel'),coins:byId('coinLabel'),combo:byId('comboLabel'),shots:byId('shotsLabel'),fact:byId('factText'),start:byId('startPanel'),result:byId('resultPanel'),toast:byId('prizeToast'),prizeMessage:byId('prizeMessage'),status:byId('gameStatus'),rainbow:byId('rainbowCount'),hammer:byId('hammerCount'),chapter:byId('chapterLabel'),mission:byId('missionLabel'),starFill:byId('starFill'),starLabel:byId('starLabel'),resultStars:byId('resultStars'),achievements:byId('achievementPanel'),achievementList:byId('achievementList'),trailMap:byId('trailMapPanel'),trailStops:byId('trailStops')};
  const reduceMotion=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false;
  const colors=['#b66a36','#d7a93d','#3d91b6','#df7b30','#c84d3f','#87a83e','#446fb8','#c7443e','#68a43e','#a83f32','#d5a13c'];
  const tileSources=['feed-sack','hay-bale','water-bucket','carrot','apple','grain-bundle','ribbon-award','puerto-rico-flag','coqui','coffee-berries','heritage-medallion'];
  const tileNames=['Feed Sack','Hay Bale','Water Bucket','Carrot','Apple','Grain Bundle','Ribbon Award','Puerto Rican Flag','Coquí','Coffee Berries','Heritage Medallion'];
  const tileImages=tileSources.map(name=>{const image=new Image();image.src=`assets/bubbles/${name}.png`;return image});
  const chapterPalettes=[
    [0,1,2,3,7],[0,1,3,4,5,6],[2,3,4,8,0,1],[2,3,4,7,6,0],[0,1,2,3,5,7],
    [0,2,3,4,7,8],[0,1,2,5,6,10],[0,1,3,4,5,6,10],[0,1,2,3,9,10],[3,4,6,7,8,9,10]
  ];
  const bubbleUnlockLevels=[1,1,1,3,13,15,17,5,23,85,67];
  const launcherImage=new Image();launcherImage.src='assets/launcher-horseshoe.png';
  const facts=[
    'The Pure Puerto Rican Paso Fino is treasured for its naturally smooth, four-beat gait.',
    'The breed developed on Puerto Rico over centuries and is part of the island’s living heritage.',
    'Careful pedigrees help conservation breeders protect rare maternal and paternal lines.',
    'Preserving a breed also preserves the stories, skills, farms, and communities built around it.',
    'DNA parent verification helps safeguard the identity of a closed, historic horse population.',
    'Every healthy foal can represent an important link between generations of Puerto Rican horses.'
  ];
  const chapters=['Harbor Beginnings','Northern Plantation Country','Rainforest Passage','Eastern Coastal Ranches','Southern Drylands','Mountain Towns','Cordillera Challenge','Western Horse Country','Coffee Hacienda Trails','Heritage Homecoming'];
  const chapterPlaces=['Historic harbor and coastal town','Northern sugar country and old estates','Eastern rainforest and river terrain','Coastal ranches and fishing towns','Dry southern plains and working farms','Interior mountain towns','Central Cordillera highlands','Western horse and breeding country','Coffee haciendas and steep farm trails','Island-wide heritage celebration'];
  const destinationMaps=['01-harbor.webp','02-plantation-country.webp','03-rainforest.webp','04-coastal-ranches.webp','05-southern-drylands.webp','06-mountain-towns.webp','07-cordillera.webp','08-western-horse-country.webp','09-coffee-trails.webp','10-heritage-homecoming.webp'];
  const destinationStops=[
    [[65,90],[34,89],[54,82],[65,70],[52,61],[31,52],[43,44],[45,33],[29,25],[31,16]],
    [[70,90],[56,84],[33,79],[39,70],[72,65],[60,55],[28,49],[40,41],[72,35],[61,25]],
    [[25,89],[44,78],[61,65],[32,58],[42,48],[70,43],[85,35],[64,27],[36,22],[56,15]],
    [[65,90],[26,87],[41,70],[75,71],[59,55],[33,47],[49,39],[50,28],[25,25],[35,19]],
    [[51,91],[80,85],[40,81],[68,72],[52,60],[61,48],[37,41],[51,31],[40,21],[31,13]],
    [[30,91],[60,81],[80,73],[77,61],[34,57],[19,43],[45,35],[75,26],[51,18],[44,10]],
    [[78,89],[33,88],[55,74],[80,61],[42,56],[61,43],[31,42],[64,29],[65,18],[40,12]],
    [[46,88],[64,81],[68,72],[44,65],[64,58],[59,49],[35,45],[38,37],[59,33],[54,25]],
    [[30,91],[70,91],[58,83],[43,72],[58,62],[34,51],[76,40],[45,31],[74,24],[45,17]],
    [[53,91],[80,85],[50,78],[34,64],[75,57],[74,44],[44,36],[32,27],[61,21],[37,15]]
  ];
  const trailStories=[
    ['Meet the Puerto Rican Paso Fino','Begin near the harbor and old town, where ships, roads, farms, and families shaped island life. Meet the breed’s naturally even four-beat gait and start following its living story.'],
    ['Plantation Country—The Whole Story','The northern coastal plain held large agricultural estates and sugar mills. This history includes wealth and development, but also slavery and exploited labor; the trail remembers the people as well as the landscape.'],
    ['Rainforest Passage','Ride into wet eastern terrain shaped by steep slopes, rivers, and heavy vegetation. Balance, careful foot placement, and calm handling matter on changing ground.'],
    ['From Ranches to Coastal Towns','Follow the shoreline through working ranches and towns. Horses helped connect farms, markets, families, and communities across the island.'],
    ['The Dry South','Puerto Rico’s southern terrain can be much drier than its rainforest. Learn how climate, water, forage, and farm management affect horses and the people caring for them.'],
    ['Mountain Towns and Working Horses','Interior communities relied on horses for transportation and farm work. A smooth gait and sure footing were practical qualities, not simply show-ring traits.'],
    ['Across the Cordillera','Cross the central mountain range in an advanced chapter about terrain, stamina, humane training, and the partnership between horse and rider.'],
    ['Families, Farms, and Breeders','Meet western horse country and the caretakers who record pedigrees, raise healthy foals, and pass practical knowledge from one generation to the next.'],
    ['Horses of Coffee Country','Explore coffee haciendas and steep farm trails while learning how pedigrees and parentage records help protect rare maternal and paternal lines.'],
    ['Carry the Legacy Home','Complete the island journey by bringing every lesson together: healthy horses, accurate records, educated owners, responsible breeding, and communities committed to the breed’s future.']
  ];
  const chapterLevelTopics=[
    ['An Island Crossroads','The Old Harbor','Ships, Horses, and Movement','Waterfront Workers','Town Markets','Roads Beyond the Port','The First Farm Trails','A Smooth Working Gait','Stories Carried Inland','Harbor Heritage Challenge'],
    ['The Northern Coastal Plain','Fields of Sugarcane','Inside the Mill','Enslaved and Exploited Labor','Workers and Working Animals','Estate Roads and Wagons','Water, Soil, and Harvests','Towns Built Around Sugar','Remembering the Whole History','Plantation Country Challenge'],
    ['Where the Rain Falls','River-Crossing Trails','Forest Footing','Hoof Care in Wet Country','Bridges and Mountain Roads','Plants of the Rainforest','Weather Changes Fast','Calm Horses, Careful Riders','Protecting Water and Forest','Rainforest Passage Challenge'],
    ['Ranches Beside the Sea','Fishing Town Connections','Salt Air and Horse Care','Coastal Markets','Fences, Gates, and Roads','Forage in the Heat','Storm Preparation','Moving Supplies and Feed','Neighbors Helping Neighbors','Coastal Ranch Challenge'],
    ['A Drier Puerto Rico','Finding and Saving Water','Pastures Under Drought','Shade and Heat Safety','Hay During Hard Seasons','Dry-Country Hoof Care','Southern Farm Roads','Community Emergency Support','Resilient Farms and Horses','Southern Drylands Challenge'],
    ['Roads Into the Interior','Steep Town Approaches','The Town Plaza','Family Mountain Farms','Pack and Riding Horses','Trades Along the Trail','Why Smooth Gait Mattered','Oral Histories and Memory','Connecting Isolated Communities','Mountain Town Challenge'],
    ['The Central Mountain Range','Balance on Steep Ground','Building Stamina Humanely','Horse and Rider Partnership','Changing Mountain Weather','Highland Farm Trails','Safe Descents and Crossings','Rest, Water, and Recovery','Conserving the Highlands','Cordillera Championship'],
    ['Western Horse Country','The Breeding Farm','Caring for Mares','Choosing Stallions Carefully','Raising Healthy Foals','Pedigrees and Farm Records','DNA Parent Verification','Registries and Identity','Veterinarians, Farriers, and Farms','Breeder Country Challenge'],
    ['Into Coffee Country','The Coffee Hacienda','Shade-Grown Hillsides','Workers of the Harvest','Horses on Steep Rows','Carrying Crops to Town','Soil, Water, and Forest','Family Lines and Farm Lines','Preserving Haciendas and Horses','Coffee Trail Challenge'],
    ['The Island Comes Together','Celebrating the Paso Fino','Training With Respect','Sharing History Publicly','Supporting Breeding Farms','Working With Registries','The Global PPR Community','Funding Conservation Work','Passing Knowledge Forward','Legacy Homecoming Championship']
  ];
  const achievementDefs=[['first_ride','First Ride','Complete your first level'],['star_student','Star Student','Earn 15 stars'],['trail_master','Trail Master','Complete 10 levels'],['combo_caballero','Combo Caballero','Reach a ×3 multiplier'],['gravity_rider','Gravity Rider','Drop 25 loose horseshoes'],['coin_keeper','Conservation Keeper','Earn 100 coins'],['power_legacy','Power of the Legacy','Use 10 power-ups'],['ppr_champion','PPR Champion','Complete all 100 levels']];
  const saved=loadProgress();
  const R=34,GAP=4,COLS=9,ROW_H=R*1.76,TOP=76; let board=[],fallingPieces=[],level=saved.level,score=saved.score,coins=saved.coins,stars=saved.stars,completed=saved.completed,stats=saved.stats,earned=new Set(saved.earned),combo=0,levelScore=0,levelDropped=0,shots=8,active=false,aim={x:360,y:500},shot=null,nextColor=0,previewColor=1,sound=saved.sound,selectedPower=null,powers=saved.powers,missesSinceDrop=0,boardYOffset=0,rowAnimating=false,bestScores=saved.bestScores,daily=saved.daily,mapMode='destination';
  function byId(id){return document.getElementById(id)}
  function loadProgress(){try{const p=JSON.parse(localStorage.getItem('horseShoePopProgress')||'{}');return{level:Math.min(100,Math.max(1,p.level||1)),score:p.score||0,coins:p.coins||0,stars:p.stars||0,completed:p.completed||{},earned:p.earned||[],powers:{rainbow:p.powers?.rainbow??2,hammer:p.powers?.hammer??2},stats:{drops:p.stats?.drops||0,powers:p.stats?.powers||0,maxCombo:p.stats?.maxCombo||0},bestScores:p.bestScores||{},daily:{last:p.daily?.last||'',streak:p.daily?.streak||0},sound:p.sound!==false}}catch{return{level:1,score:0,coins:0,stars:0,completed:{},earned:[],powers:{rainbow:2,hammer:2},stats:{drops:0,powers:0,maxCombo:0},bestScores:{},daily:{last:'',streak:0},sound:true}}}
  function saveProgress(){try{localStorage.setItem('horseShoePopProgress',JSON.stringify({level,score,coins,stars,completed,earned:[...earned],powers,stats,bestScores,daily,sound,lastPlayed:new Date().toISOString()}));return true}catch(error){console.warn('Horse Shoe Pop progress could not be saved.',error);announce('Progress could not be saved on this device.');return false}}
  function loadSession(){try{const session=JSON.parse(localStorage.getItem('horseShoePopSession')||'null');return session&&Date.now()-(session.updated||0)<1000*60*60*24*30?session:null}catch{return null}}
  function saveSession(){if(!board.length||shot||rowAnimating)return false;try{localStorage.setItem('horseShoePopSession',JSON.stringify({version:2,updated:Date.now(),level,board,combo,levelScore,levelDropped,shots,nextColor,previewColor,missesSinceDrop,selectedPower}));return true}catch(error){console.warn('Horse Shoe Pop session could not be saved.',error);announce('This unfinished board could not be saved on this device.');return false}}
  function clearSession(){try{localStorage.removeItem('horseShoePopSession')}catch(error){console.warn('Horse Shoe Pop session could not be cleared.',error)}}
  function restoreSession(){const session=loadSession();if(!session||session.level!==level||!Array.isArray(session.board)||!session.board.length)return false;board=session.board;combo=session.combo||0;levelScore=session.levelScore||0;levelDropped=session.levelDropped||0;shots=session.shots??levelConfig().shots;nextColor=session.nextColor??randomBoardColor();previewColor=session.previewColor??randomBoardColor();missesSinceDrop=session.missesSinceDrop||0;selectedPower=session.selectedPower||null;shot=null;fallingPieces=[];boardYOffset=0;rowAnimating=false;return true}
  function grantDailyReward(){const now=new Date(),today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;if(daily.last===today)return'';const previous=daily.last?new Date(`${daily.last}T00:00:00`):null,diff=previous?Math.round((new Date(`${today}T00:00:00`)-previous)/86400000):99;daily.streak=diff===1?daily.streak+1:1;daily.last=today;const reward=5+Math.min(10,daily.streak);coins+=reward;let bonus='';if(daily.streak%3===0){powers.rainbow++;bonus=' + Rainbow Shoe'}saveProgress();return `Daily Trail Reward • ${reward} coins${bonus} • ${daily.streak}-day streak`}
  function levelConfig(){const chapter=Math.min(9,Math.floor((level-1)/10)),step=(level-1)%10,boss=step===9,palette=Math.min(chapterPalettes[chapter].length,3+Math.floor(step/2));return{chapter,step,boss,type:boss?4:step%5,goal:(650+level*125)*(boss?1.45:1),dropGoal:4+Math.floor(level/6)+(boss?5:0),comboGoal:2+Math.floor(level/18)+(boss?1:0),rows:boss?8:Math.min(4+Math.floor(level/12),7),palette,shots:boss?Math.max(5,9-Math.floor(level/20)):Math.max(6,12-Math.floor(level/14)),fill:boss?.98:Math.min(.95,.82+level*.0015),rowDropEvery:level<4?0:boss?3:level<25?5:level<60?4:3}}
  function activePalette(cfg=levelConfig()){return chapterPalettes[cfg.chapter].slice(0,cfg.palette)}
  function setup(allowResume=false){if(allowResume&&restoreSession()){updateUI();return true}board=[];fallingPieces=[];combo=0;levelScore=0;levelDropped=0;missesSinceDrop=0;boardYOffset=0;rowAnimating=false;selectedPower=null;const cfg=levelConfig(),palette=activePalette(cfg);for(let r=0;r<cfg.rows;r++){board[r]=[];for(let c=0;c<COLS-(r%2);c++){board[r][c]=Math.random()<cfg.fill?palette[Math.floor(Math.random()*palette.length)]:null}}shots=cfg.shots;nextColor=randomBoardColor();previewColor=randomBoardColor();shot=null;updateUI();saveSession();return false}
  function randomBoardColor(){const present=[...new Set(board.flat().filter(Number.isInteger))];return present.length?present[Math.floor(Math.random()*present.length)]:Math.floor(Math.random()*colors.length)}
  function pos(r,c){return{x:R+GAP+c*(R*2+GAP)+(r%2)*(R+GAP/2),y:TOP+r*ROW_H+boardYOffset}}
  function cellFrom(x,y){const r=Math.max(0,Math.round((y-TOP)/ROW_H)),offset=(r%2)*(R+GAP/2),c=Math.max(0,Math.min(COLS-1-(r%2),Math.round((x-R-GAP-offset)/(R*2+GAP))));return{r,c}}
  function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);drawRope();for(let r=0;r<board.length;r++)for(let c=0;c<(board[r]?.length||0);c++)if(board[r][c]!=null){const p=pos(r,c);drawBubble(p.x,p.y,board[r][c],R)}drawFalling();if(active&&!shot)drawGuide();if(shot)drawBubble(shot.x,shot.y,shot.color,R);drawLauncher();requestAnimationFrame(draw)}
  function drawFalling(){fallingPieces.forEach(piece=>{piece.vy+=.42;piece.y+=piece.vy;piece.rotation+=piece.spin;ctx.save();ctx.globalAlpha=Math.max(0,1-(piece.y-canvas.height*.72)/(canvas.height*.35));ctx.translate(piece.x,piece.y);ctx.rotate(piece.rotation);drawBubble(0,0,piece.color,R);ctx.restore()});fallingPieces=fallingPieces.filter(piece=>piece.y<canvas.height+R*3)}
  function shoeColor(code){return code===-1?'#f8f4ff':code===-2?'#8a6840':colors[code]}
  function drawRope(){ctx.save();ctx.strokeStyle='#d7b47288';ctx.lineWidth=5;ctx.setLineDash([13,9]);ctx.beginPath();ctx.moveTo(0,42);ctx.lineTo(canvas.width,42);ctx.stroke();ctx.restore()}
  function drawBubble(x,y,code,r){const icon=tileImages[code];ctx.save();ctx.translate(x,y);ctx.shadowColor='#100703cc';ctx.shadowBlur=8;ctx.shadowOffsetY=5;if(icon?.complete&&icon.naturalWidth){ctx.beginPath();ctx.arc(0,0,r*.93,0,Math.PI*2);ctx.clip();ctx.drawImage(icon,-r,-r,r*2,r*2)}else{const glass=ctx.createRadialGradient(-r*.28,-r*.32,2,0,0,r);glass.addColorStop(0,'#fffdf4');glass.addColorStop(.2,shoeColor(code));glass.addColorStop(1,'#241208');ctx.fillStyle=glass;ctx.beginPath();ctx.arc(0,0,r*.88,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#f2cf8d';ctx.lineWidth=2;ctx.stroke()}ctx.restore()}
  function drawShoe(x,y,color,r,icon){ctx.save();ctx.translate(x,y);ctx.lineCap='round';ctx.shadowColor='#100703cc';ctx.shadowBlur=7;ctx.shadowOffsetY=4;const bubble=ctx.createRadialGradient(-r*.15,-r*.18,2,0,0,r*.54);bubble.addColorStop(0,'#fff7d9');bubble.addColorStop(.28,color);bubble.addColorStop(1,'#241208');const metal=ctx.createLinearGradient(-r,-r,r,r);metal.addColorStop(0,'#fff2b7');metal.addColorStop(.17,'#cf9239');metal.addColorStop(.48,'#4b250d');metal.addColorStop(.72,'#e2ae52');metal.addColorStop(1,'#623112');ctx.strokeStyle='#190b04';ctx.lineWidth=r*.88;ctx.beginPath();ctx.arc(0,0,r*.68,.08*Math.PI,.92*Math.PI,true);ctx.stroke();ctx.strokeStyle=metal;ctx.lineWidth=r*.72;ctx.stroke();ctx.shadowColor='transparent';ctx.strokeStyle='#2d1609';ctx.lineWidth=r*.48;ctx.stroke();ctx.strokeStyle='#f0c568';ctx.lineWidth=r*.1;ctx.stroke();ctx.shadowColor='#100703aa';ctx.shadowBlur=4;ctx.fillStyle=bubble;ctx.beginPath();ctx.arc(0,0,r*.4,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#f4d98f';ctx.lineWidth=1.5;ctx.stroke();ctx.shadowColor='transparent';if(icon?.complete){ctx.save();ctx.beginPath();ctx.arc(0,0,r*.34,0,Math.PI*2);ctx.clip();ctx.drawImage(icon,-r*.37,-r*.37,r*.74,r*.74);ctx.restore();ctx.fillStyle='#fff8db44';ctx.beginPath();ctx.ellipse(-r*.1,-r*.15,r*.16,r*.07,-.4,0,Math.PI*2);ctx.fill()}for(const a of [.12,.31,.69,.88]){const q=a*Math.PI,px=Math.cos(q)*r*.68,py=Math.sin(q)*r*.68;ctx.fillStyle='#160a04';ctx.beginPath();ctx.arc(px,py,4.1,0,7);ctx.fill();ctx.fillStyle='#f4ca73';ctx.beginPath();ctx.arc(px-1,py-1,1.9,0,7);ctx.fill()}ctx.restore()}
  function drawLauncher(){const x=canvas.width/2,y=canvas.height-70,code=selectedPower==='rainbow'?-1:selectedPower==='hammer'?-2:nextColor;ctx.save();ctx.shadowColor='#0b0502dd';ctx.shadowBlur=18;ctx.shadowOffsetY=9;if(launcherImage.complete&&launcherImage.naturalWidth)ctx.drawImage(launcherImage,x-92,y-108,184,200);ctx.shadowColor='transparent';drawBubble(x,y,code,32);ctx.fillStyle='#f2c667';ctx.font='700 10px Montserrat';ctx.textAlign='center';ctx.fillText(selectedPower?'POWER SHOE':'CURRENT',x,y-108);ctx.strokeStyle='#7a4b22';ctx.lineWidth=9;ctx.beginPath();ctx.arc(x+108,y+6,43,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#e1b45b';ctx.lineWidth=3;ctx.stroke();drawBubble(x+108,y+6,previewColor,34);ctx.fillStyle='#f2c667';ctx.fillText('NEXT',x+108,y-47);ctx.restore()}
  function drawGuide(){const x=canvas.width/2,y=canvas.height-94,dx=aim.x-x,dy=Math.min(-40,aim.y-y),len=Math.hypot(dx,dy);let ux=dx/len,uy=dy/len,px=x,py=y,remaining=620;ctx.save();ctx.shadowColor='#ffc447';ctx.shadowBlur=7;ctx.strokeStyle='#ffe49ddd';ctx.lineWidth=3.5;ctx.setLineDash([7,11]);ctx.beginPath();ctx.moveTo(px,py);for(let bounce=0;bounce<3&&remaining>0;bounce++){const wallX=ux>0?canvas.width-R:R,wallT=Math.abs(ux)>.001?(wallX-px)/ux:Infinity,topT=uy<0?(TOP-py)/uy:Infinity,nextT=Math.min(remaining,wallT>0?wallT:Infinity,topT>0?topT:Infinity);px+=ux*nextT;py+=uy*nextT;ctx.lineTo(px,py);remaining-=nextT;if(nextT===topT||remaining<=0)break;if(nextT===wallT){ux*=-1;px+=ux*.5}}ctx.stroke();ctx.restore()}
  function pointer(e){const rect=canvas.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:(p.clientX-rect.left)*canvas.width/rect.width,y:(p.clientY-rect.top)*canvas.height/rect.height}}
  function aimAt(e){if(!active||shot)return;aim=pointer(e)}
  function fire(e){if(!active||shot||rowAnimating)return;e?.preventDefault?.();if(e&&(e.touches?.length||Number.isFinite(e.clientX)))aimAt(e);const x=canvas.width/2,y=canvas.height-71,dx=aim.x-x,dy=Math.min(-50,aim.y-y),len=Math.hypot(dx,dy),power=selectedPower;shot={x,y,vx:dx/len*14,vy:dy/len*14,color:power==='rainbow'?-1:power==='hammer'?-2:nextColor};if(power){powers[power]--;stats.powers++;selectedPower=null}else{nextColor=previewColor;previewColor=randomBoardColor()}updateUI();soundCue('fire');tick()}
  function tick(){if(!shot)return;shot.x+=shot.vx;shot.y+=shot.vy;if(shot.x<R||shot.x>canvas.width-R){shot.vx*=-1;shot.x=Math.max(R,Math.min(canvas.width-R,shot.x));soundCue('bank')}let hit=shot.y<TOP,hitCell=null;for(let r=0;!hit&&r<board.length;r++)for(let c=0;c<(board[r]?.length||0);c++)if(board[r][c]!=null){const p=pos(r,c);if(Math.hypot(shot.x-p.x,shot.y-p.y)<R*1.82){hit=true;hitCell={r,c};break}}let target=null;if(hitCell){target=neighbors(hitCell.r,hitCell.c).filter(([r,c])=>board[r]?.[c]==null).sort((a,b)=>{const ap=pos(a[0],a[1]),bp=pos(b[0],b[1]);return Math.hypot(shot.x-ap.x,shot.y-ap.y)-Math.hypot(shot.x-bp.x,shot.y-bp.y)})[0]}if(hit)settleShot(target||Object.values(cellFrom(shot.x,shot.y)));else requestAnimationFrame(tick)}
  function settleShot(target){const startX=shot.x,startY=shot.y,p=pos(target[0],target[1]),began=performance.now(),duration=reduceMotion?1:165;function step(now){if(!shot)return;const t=Math.min(1,(now-began)/duration),ease=1-Math.pow(1-t,3);shot.x=startX+(p.x-startX)*ease;shot.y=startY+(p.y-startY)*ease;if(t<1)requestAnimationFrame(step);else{soundCue('settle');land()}}requestAnimationFrame(step)}
  function addScore(gain){score+=gain;levelScore+=gain;coins+=Math.max(1,Math.floor(gain/100))}
  function land(){const cell=cellFrom(shot.x,shot.y);while(board.length<=cell.r)board.push(Array(COLS-(board.length%2)).fill(null));while(board[cell.r].length<COLS-(cell.r%2))board[cell.r].push(null);let c=cell.c;if(shot.color===-2){const smashed=[[cell.r,c],...neighbors(cell.r,c)];let removed=0;smashed.forEach(([r,k])=>{if(board[r]?.[k]!=null){board[r][k]=null;removed++}});shot=null;combo++;addScore(removed*45);showPrize(`Ranch Hammer! ${removed} horseshoes cleared`);soundCue('power');afterLand(true);return}if(board[cell.r][c]!=null){const tries=[[cell.r+1,c],[cell.r+1,c-1],[cell.r,c+1],[cell.r,c-1]].filter(([r,k])=>r>=0&&k>=0);const open=tries.find(([r,k])=>board[r]?.[k]==null);if(open){cell.r=open[0];c=open[1];while(board.length<=cell.r)board.push(Array(COLS-(cell.r%2)).fill(null))}}if(shot.color===-1){const touching=neighbors(cell.r,c).map(([r,k])=>board[r]?.[k]).filter(Number.isInteger);shot.color=touching[0]??randomBoardColor();showPrize('Rainbow Shoe matched the trail!')}board[cell.r][c]=shot.color;const matched=flood(cell.r,c,shot.color);shot=null;if(matched.length>=3){matched.forEach(([r,k])=>board[r][k]=null);const dropped=dropLoose();combo++;stats.maxCombo=Math.max(stats.maxCombo,combo);const multiplier=1+Math.floor(combo/3),gain=(matched.length*20+dropped*35)*multiplier;addScore(gain);if(combo%3===0){coins+=5;shots++;powers[Math.random()<.5?'rainbow':'hammer']++;showPrize(`Combo Prize! ×${multiplier} • +5 coins • +1 shot`);soundCue('prize')}else soundCue('match');afterLand(true)}else{combo=0;shots--;soundCue('miss');afterLand(false)}}
  function missionComplete(){const cfg=levelConfig(),empty=board.flat().filter(Number.isInteger).length===0;return empty||(cfg.type===1&&levelScore>=cfg.goal)||(cfg.type===2&&levelDropped>=cfg.dropGoal)||(cfg.type===3&&1+Math.floor(combo/3)>=cfg.comboGoal)||(cfg.type===4&&levelScore>=cfg.goal)}
  function afterLand(success){trim();updateUI();const cfg=levelConfig();if(!success&&cfg.rowDropEvery&&++missesSinceDrop>=cfg.rowDropEvery){missesSinceDrop=0;dropPressureRow(resolveAfterLand);return}resolveAfterLand()}
  function resolveAfterLand(){updateUI();if(missionComplete())finish(true);else if(shots<=0||board.length*ROW_H+TOP>canvas.height-180)finish(false);else{saveProgress();saveSession()}}
  function dropPressureRow(done){
    rowAnimating=true;
    const cfg=levelConfig(),palette=activePalette(cfg),fresh=Array.from({length:COLS},()=>palette[Math.floor(Math.random()*palette.length)]),shifted=[fresh];
    board.forEach((row,index)=>{const expected=COLS-((index+1)%2),copy=row.slice(0,expected);while(copy.length<expected)copy.push(null);shifted.push(copy)});
    board=shifted;boardYOffset=-ROW_H;showPrize('Trail pressure! A new horseshoe row is dropping in.');soundCue('row');
    announce('Pressure row added. The horseshoes moved down.');
    const began=performance.now(),duration=reduceMotion?1:340;function step(now){const t=Math.min(1,(now-began)/duration);boardYOffset=-ROW_H*(1-(1-Math.pow(1-t,3)));if(t<1)requestAnimationFrame(step);else{boardYOffset=0;rowAnimating=false;soundCue('thud');done()}}requestAnimationFrame(step)
  }
  function announce(message){if(!ui.status)return;ui.status.textContent='';requestAnimationFrame(()=>{ui.status.textContent=message})}
  function showPrize(message){ui.prizeMessage.textContent=message;ui.toast.classList.remove('show');void ui.toast.offsetWidth;ui.toast.classList.add('show');announce(message)}
  function neighbors(r,c){const d=r%2?[[0,-1],[0,1],[-1,0],[-1,1],[1,0],[1,1]]:[[0,-1],[0,1],[-1,-1],[-1,0],[1,-1],[1,0]];return d.map(([a,b])=>[r+a,c+b]).filter(([a,b])=>a>=0&&b>=0&&b<(COLS-(a%2)))}
  function flood(r,c,color){const out=[],seen=new Set(),q=[[r,c]];while(q.length){const p=q.pop(),key=p.join(':');if(seen.has(key)||board[p[0]]?.[p[1]]!==color)continue;seen.add(key);out.push(p);q.push(...neighbors(...p))}return out}
  function dropLoose(){const keep=new Set(),q=[];(board[0]||[]).forEach((v,c)=>{if(v!=null)q.push([0,c])});while(q.length){const p=q.pop(),key=p.join(':');if(keep.has(key)||board[p[0]]?.[p[1]]==null)continue;keep.add(key);q.push(...neighbors(...p))}let n=0;for(let r=0;r<board.length;r++)for(let c=0;c<board[r].length;c++)if(board[r][c]!=null&&!keep.has(r+':'+c)){const p=pos(r,c);fallingPieces.push({x:p.x,y:p.y,color:board[r][c],vy:2+Math.random()*2,rotation:0,spin:(Math.random()-.5)*.12});board[r][c]=null;n++}if(n){levelDropped+=n;stats.drops+=n;showPrize(`${n} unsupported horseshoe${n===1?'':'s'} fell! Bonus points awarded.`);soundCue('fall')}return n}
  function trim(){while(board.length&&board[board.length-1].every(v=>v==null))board.pop()}
  function missionText(cfg=levelConfig()){const goal=cfg.type===0?'Clear every bubble':cfg.type===1?`Earn ${Math.round(cfg.goal).toLocaleString()} points`:cfg.type===2?`Drop ${cfg.dropGoal} loose bubbles`:cfg.type===3?`Reach a ×${cfg.comboGoal} combo`:`Fill the feed wagon • ${Math.round(cfg.goal).toLocaleString()} points`;return cfg.boss?`CHAMPIONSHIP • ${goal}`:goal}
  function challengeReward(cfg=levelConfig()){return cfg.boss?'Championship reward: 3 stars + bonus Conservation Coins':'Reward: up to 3 Heritage Stars'}
  function renderTrailMap(required=false,mode=mapMode){
    mapMode=mode;
    const cfg=levelConfig(),story=trailStories[cfg.chapter],levelTopic=chapterLevelTopics[cfg.chapter][cfg.step],stage=document.querySelector('.island-map-stage'),isDestination=mapMode==='destination';
    stage.classList.toggle('destination-mode',isDestination);
    stage.style.setProperty('--destination-map',`url('assets/destinations/${destinationMaps[cfg.chapter]}')`);
    byId('trailMapTitle').textContent=isDestination?chapters[cfg.chapter]:'Puerto Rico Heritage Trail';
    byId('trailMapProgress').textContent=isDestination?`Destination ${cfg.chapter+1} of 10 • Game ${cfg.step+1} of 10`:`Island journey • ${cfg.chapter+1} of 10 destinations reached`;
    byId('trailPlaceLabel').textContent=chapterPlaces[cfg.chapter];
    byId('trailStoryLabel').textContent=cfg.boss?'Why this championship is here':'Why this stop is on the map';
    byId('trailStoryTitle').textContent=levelTopic;
    byId('trailStoryText').textContent=`${story[1]} Game ${cfg.step+1} of this destination explores “${levelTopic}.”`;
    byId('trailChallengeLabel').textContent=cfg.boss?'Super-hard championship challenge':'Next challenge';
    byId('trailChallengeText').textContent=missionText(cfg);
    const palette=activePalette(cfg),justUnlocked=cfg.step>0&&cfg.step%2===0&&cfg.palette>3?` • New bubble topic: ${tileNames[palette[palette.length-1]]}`:'';
    const pressure=cfg.rowDropEvery?` • New row after ${cfg.rowDropEvery} missed shots`:'';
    byId('trailChallengeReward').textContent=challengeReward(cfg)+justUnlocked+pressure;
    byId('rideTrailBtn').textContent=level===100&&completed[100]?'Ride Level 100 Again':`Play Game ${cfg.step+1} • Level ${level}`;
    byId('closeTrailMap').hidden=required;
    const highestCompleted=Math.max(0,...Object.keys(completed).map(Number)),unlockedLevel=Math.min(100,Math.max(level,highestCompleted+1)),unlockedChapter=Math.floor((unlockedLevel-1)/10);
    if(isDestination){
      const start=cfg.chapter*10+1,positions=destinationStops[cfg.chapter];
      ui.trailStops.setAttribute('aria-label',`${chapters[cfg.chapter]} game trail`);
      ui.trailStops.innerHTML=Array.from({length:10},(_,i)=>{const target=start+i,isDone=Boolean(completed[target]),isCurrent=target===level,isLocked=target>unlockedLevel,[left,top]=positions[i];return `<button class="trail-stop ${isDone?'completed':''} ${isCurrent?'current':''} ${isLocked?'locked':''}" style="left:${left}%;top:${top}%" data-level="${target}" ${isLocked?'disabled':''} title="Game ${i+1}: ${chapterLevelTopics[cfg.chapter][i]}" aria-label="Game ${i+1}: ${chapterLevelTopics[cfg.chapter][i]}${isDone?', completed':''}${isCurrent?', current game':''}">${isDone?'★':i+1}</button>`}).join('');
      ui.trailStops.querySelectorAll('button:not(:disabled)').forEach(button=>button.onclick=()=>{level=Number(button.dataset.level);saveProgress();renderTrailMap(required,'destination');updateUI()});
    }else{
      ui.trailStops.setAttribute('aria-label','Island destination stops');
      ui.trailStops.innerHTML=chapters.map((name,i)=>{const start=i*10+1,isDone=Array.from({length:10},(_,step)=>Boolean(completed[start+step])).every(Boolean),isCurrent=i===cfg.chapter,isLocked=i>unlockedChapter,target=isCurrent?level:Math.min(start+9,Math.max(start,highestCompleted+1));return `<button class="trail-stop ${isDone?'completed':''} ${isCurrent?'current':''} ${isLocked?'locked':''}" data-level="${target}" ${isLocked?'disabled':''} title="${name} — ${chapterPlaces[i]}" aria-label="Destination ${i+1}: ${name}${isDone?', completed':''}${isCurrent?', current destination':''}">${isDone?'★':i+1}</button>`}).join('');
      ui.trailStops.querySelectorAll('button:not(:disabled)').forEach(button=>button.onclick=()=>{level=Number(button.dataset.level);saveProgress();renderTrailMap(required,'destination');updateUI()});
    }
    byId('islandOverviewBtn').classList.toggle('active',!isDestination);
    byId('destinationMapBtn').classList.toggle('active',isDestination);
    byId('bubbleCollection').innerHTML=tileSources.map((source,i)=>{const unlocked=level>=bubbleUnlockLevels[i];return `<figure class="bubble-collect-item ${unlocked?'unlocked':'locked'}"><img src="assets/bubbles/${source}.png" alt="${tileNames[i]}"><figcaption>${unlocked?tileNames[i]:`Level ${bubbleUnlockLevels[i]}`}</figcaption></figure>`}).join('');
  }
  function openTrailMap(required=false,mode='destination'){
    ui.trailMap.dataset.resume=!required&&active?'1':'0';
    ui.trailMap.dataset.required=required?'1':'0';
    active=false;
    renderTrailMap(required,mode);
    ui.trailMap.classList.add('open');
    byId('trailMapTitle').setAttribute('tabindex','-1');
    byId('trailMapTitle').focus();
  }
  function closeTrailMap(resume=false){ui.trailMap.classList.remove('open');if(resume){active=true;canvas.focus()}else byId('trailBtn').focus();updateUI()}
  function levelStars(){const cfg=levelConfig(),base=levelScore>=cfg.goal?1:0,skill=levelDropped>=cfg.dropGoal||stats.maxCombo>=cfg.comboGoal*3?1:0,finish=board.flat().filter(Number.isInteger).length===0?1:0;return Math.min(3,base+skill+finish)}
  function updateUI(){const cfg=levelConfig(),s=levelStars(),pressure=cfg.rowDropEvery?` • New row in ${cfg.rowDropEvery-missesSinceDrop} misses`:'';ui.level.textContent=`${level}/100`;ui.score.textContent=score.toLocaleString();ui.coins.textContent=coins;ui.combo.textContent=`×${1+Math.floor(combo/3)}`;ui.shots.textContent=shots;ui.rainbow.textContent=powers.rainbow;ui.hammer.textContent=powers.hammer;ui.chapter.textContent=`Chapter ${cfg.chapter+1} • ${chapters[cfg.chapter]}`;ui.mission.textContent=missionText(cfg)+pressure;ui.starFill.style.width=`${Math.min(100,levelScore/cfg.goal*100)}%`;ui.starLabel.textContent=`${s} / 3 stars`;['rainbow','hammer'].forEach(name=>{const button=byId(name+'Power');button.disabled=!powers[name]||!active||rowAnimating;button.classList.toggle('selected',selectedPower===name);button.setAttribute('aria-pressed',selectedPower===name?'true':'false')})}
  function checkAchievements(){const tests={first_ride:Object.keys(completed).length>=1,star_student:stars>=15,trail_master:Object.keys(completed).length>=10,combo_caballero:stats.maxCombo>=6,gravity_rider:stats.drops>=25,coin_keeper:coins>=100,power_legacy:stats.powers>=10,ppr_champion:Object.keys(completed).length>=100};achievementDefs.forEach(([id,name])=>{if(tests[id]&&!earned.has(id)){earned.add(id);coins+=10;showPrize(`Achievement unlocked: ${name} • +10 coins`)}})}
  function finish(win){active=false;clearSession();let earnedStars=0;if(win){earnedStars=Math.max(1,levelStars());const old=completed[level]||0;completed[level]=Math.max(old,earnedStars);stars+=Math.max(0,earnedStars-old);coins+=earnedStars*3;bestScores[level]=Math.max(bestScores[level]||0,levelScore);checkAchievements();saveProgress();soundCue('win')}const destinationComplete=level%10===0;byId('resultEyebrow').textContent=win?'Mission Complete':'Trail Paused';byId('resultTitle').textContent=win?(level===100?'PPR Legacy Champion!':destinationComplete?'New Island Trail Unlocked!':'Heritage Trail Restored!'):'Give It Another Ride';byId('resultText').textContent=win?`Level ${level} complete • ${earnedStars*3} prize coins earned. You now have ${stars} heritage stars.${destinationComplete&&level<100?' The next island destination is now open.':''}`:'Match groups of three before the bubbles reach the rider. Your overall score and collected rewards are safe.';ui.resultStars.textContent=win?'★'.repeat(earnedStars)+'☆'.repeat(3-earnedStars):'☆☆☆';byId('nextBtn').textContent=win?(destinationComplete?'Open Island Trail':'Continue Destination'):'Try This Level Again';ui.fact.textContent=facts[(level)%facts.length];ui.result.classList.add('open');ui.result.dataset.win=win?'1':'0';ui.result.dataset.destinationComplete=destinationComplete?'1':'0';byId('resultTitle').setAttribute('tabindex','-1');byId('resultTitle').focus()}
  function tone(freq,duration,type='sine',gain=.04,delay=0){if(!sound)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const ac=tone.ac||(tone.ac=new A()),o=ac.createOscillator(),g=ac.createGain(),start=ac.currentTime+delay;o.frequency.value=freq;o.type=type;g.gain.setValueAtTime(gain,start);g.gain.exponentialRampToValueAtTime(.001,start+duration);o.connect(g).connect(ac.destination);o.start(start);o.stop(start+duration)}
  function soundCue(name){const cues={fire:[[430,.05,'triangle',.035,0],[610,.06,'sine',.025,.035]],bank:[[235,.035,'square',.018,0]],settle:[[310,.045,'triangle',.025,0]],match:[[620,.08,'sine',.04,0],[820,.11,'sine',.04,.075]],miss:[[170,.12,'triangle',.035,0]],fall:[[360,.08,'triangle',.03,0],[260,.1,'triangle',.03,.07],[170,.13,'triangle',.03,.15]],power:[[190,.08,'square',.03,0],[440,.15,'triangle',.04,.08]],prize:[[520,.08,'sine',.04,0],[660,.08,'sine',.04,.09],[880,.16,'sine',.04,.18]],row:[[330,.08,'triangle',.03,0],[260,.08,'triangle',.03,.1],[210,.12,'triangle',.04,.2]],thud:[[105,.18,'square',.045,0]],win:[[520,.1,'sine',.04,0],[660,.1,'sine',.04,.1],[880,.2,'sine',.045,.2]],start:[[330,.08,'sine',.03,0],[495,.12,'sine',.035,.08]]};(cues[name]||[]).forEach(args=>tone(...args))}
  function choosePower(name){if(!active||shot||!powers[name])return;selectedPower=selectedPower===name?null:name;updateUI();saveSession();showPrize(selectedPower?`${name==='rainbow'?'Rainbow Shoe':'Ranch Hammer'} ready — aim and fire`:'Power-up returned')}
  function renderAchievements(){ui.achievementList.innerHTML=achievementDefs.map(([id,name,desc])=>`<article class="achievement ${earned.has(id)?'earned':''}"><span>${earned.has(id)?'★':'☆'}</span><div><b>${name}</b><small>${desc}</small></div><em>${earned.has(id)?'Earned':'+10 coins'}</em></article>`).join('')}
  byId('startBtn').onclick=()=>{ui.start.classList.remove('open');active=true;updateUI();soundCue('start')};
  byId('nextBtn').onclick=()=>{const won=ui.result.dataset.win==='1',destinationComplete=ui.result.dataset.destinationComplete==='1';ui.result.classList.remove('open');if(won){if(level<100)level++;saveProgress();openTrailMap(true,destinationComplete?'island':'destination')}else{setup();active=true;updateUI()}};
  byId('rideTrailBtn').onclick=()=>{ui.start.classList.remove('open');closeTrailMap(false);setup(true);active=true;updateUI();canvas.focus();soundCue('start')};
  byId('trailBtn').onclick=()=>openTrailMap(false,'destination');
  byId('islandOverviewBtn').onclick=()=>renderTrailMap(ui.trailMap.dataset.required==='1','island');
  byId('destinationMapBtn').onclick=()=>renderTrailMap(ui.trailMap.dataset.required==='1','destination');
  byId('closeTrailMap').onclick=()=>closeTrailMap(ui.trailMap.dataset.resume==='1');
  byId('soundBtn').onclick=()=>{sound=!sound;byId('soundBtn').textContent=sound?'♪':'×';byId('soundBtn').setAttribute('aria-pressed',sound?'true':'false');announce(sound?'Sound on':'Sound off');saveProgress()};byId('rainbowPower').onclick=()=>choosePower('rainbow');byId('hammerPower').onclick=()=>choosePower('hammer');byId('achievementBtn').onclick=()=>{renderAchievements();ui.achievements.classList.add('open');byId('achievementTitle').setAttribute('tabindex','-1');byId('achievementTitle').focus()};byId('closeAchievements').onclick=()=>{ui.achievements.classList.remove('open');byId('achievementBtn').focus()};
  function keyboardControl(event){const openOverlay=document.querySelector('.overlay.open');if(openOverlay||!active||shot||rowAnimating)return;if(event.key==='ArrowLeft'){event.preventDefault();aim.x=Math.max(R+8,aim.x-38)}else if(event.key==='ArrowRight'){event.preventDefault();aim.x=Math.min(canvas.width-R-8,aim.x+38)}else if(event.key==='ArrowUp'){event.preventDefault();aim={x:canvas.width/2,y:TOP}}else if(event.key===' '||event.key==='Enter'){event.preventDefault();fire(event)}}
  canvas.addEventListener('keydown',keyboardControl);
  document.addEventListener('keydown',event=>{if(event.key!=='Escape')return;if(ui.achievements.classList.contains('open')){ui.achievements.classList.remove('open');byId('achievementBtn').focus()}else if(ui.trailMap.classList.contains('open')&&!byId('closeTrailMap').hidden)closeTrailMap(ui.trailMap.dataset.resume==='1')});
  canvas.addEventListener('pointerdown',()=>canvas.focus());
  canvas.addEventListener('mousemove',aimAt);canvas.addEventListener('touchmove',aimAt,{passive:true});canvas.addEventListener('click',fire);canvas.addEventListener('touchend',e=>{if(active&&!shot){const t=e.changedTouches[0],rect=canvas.getBoundingClientRect();aim={x:(t.clientX-rect.left)*canvas.width/rect.width,y:(t.clientY-rect.top)*canvas.height/rect.height};fire({preventDefault(){},clientX:t.clientX,clientY:t.clientY})}},{passive:false});
  const dailyMessage=grantDailyReward(),resumed=setup(true);byId('soundBtn').textContent=sound?'♪':'×';byId('soundBtn').setAttribute('aria-pressed',sound?'true':'false');if(resumed)byId('startBtn').textContent='Continue Ride';if(dailyMessage){byId('dailyRewardText').hidden=false;byId('dailyRewardText').textContent=dailyMessage}document.addEventListener('visibilitychange',()=>{if(document.hidden&&active&&!shot&&!rowAnimating){saveProgress();saveSession()}});window.addEventListener('beforeunload',()=>{if(active&&!shot&&!rowAnimating){saveProgress();saveSession()}});draw();
})();
