(() => {
  'use strict';
  const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d');
  const ui={level:byId('levelLabel'),score:byId('scoreLabel'),coins:byId('coinLabel'),combo:byId('comboLabel'),shots:byId('shotsLabel'),fact:byId('factText'),start:byId('startPanel'),result:byId('resultPanel'),toast:byId('prizeToast'),prizeMessage:byId('prizeMessage'),rainbow:byId('rainbowCount'),hammer:byId('hammerCount')};
  const colors=['#e95f54','#f0bd46','#45a879','#478fc1','#8a64aa'];
  const facts=[
    'The Pure Puerto Rican Paso Fino is treasured for its naturally smooth, four-beat gait.',
    'The breed developed on Puerto Rico over centuries and is part of the island’s living heritage.',
    'Careful pedigrees help conservation breeders protect rare maternal and paternal lines.',
    'Preserving a breed also preserves the stories, skills, farms, and communities built around it.',
    'DNA parent verification helps safeguard the identity of a closed, historic horse population.',
    'Every healthy foal can represent an important link between generations of Puerto Rican horses.'
  ];
  const R=30,GAP=7,COLS=10,ROW_H=R*1.78,TOP=70; let board=[],fallingPieces=[],level=1,score=0,coins=0,combo=0,shots=8,active=false,aim={x:360,y:500},shot=null,nextColor=0,sound=true,selectedPower=null,powers={rainbow:1,hammer:1};
  function byId(id){return document.getElementById(id)}
  function setup(){board=[];fallingPieces=[];combo=0;selectedPower=null;const rows=Math.min(4+Math.floor(level/2),7),palette=Math.min(3+Math.floor(level/2),colors.length);for(let r=0;r<rows;r++){board[r]=[];for(let c=0;c<COLS-(r%2);c++){board[r][c]=Math.random()<.9?Math.floor(Math.random()*palette):null}}shots=Math.max(5,9-Math.floor(level/2));nextColor=randomBoardColor();shot=null;updateUI()}
  function randomBoardColor(){const present=[...new Set(board.flat().filter(Number.isInteger))];return present.length?present[Math.floor(Math.random()*present.length)]:Math.floor(Math.random()*colors.length)}
  function pos(r,c){return{x:R+GAP+c*(R*2+GAP)+(r%2)*(R+GAP/2),y:TOP+r*ROW_H}}
  function cellFrom(x,y){const r=Math.max(0,Math.round((y-TOP)/ROW_H)),offset=(r%2)*(R+GAP/2),c=Math.max(0,Math.min(COLS-1-(r%2),Math.round((x-R-GAP-offset)/(R*2+GAP))));return{r,c}}
  function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);drawRope();for(let r=0;r<board.length;r++)for(let c=0;c<(board[r]?.length||0);c++)if(board[r][c]!=null){const p=pos(r,c);drawShoe(p.x,p.y,shoeColor(board[r][c]),R)}drawFalling();if(active&&!shot)drawGuide();if(shot)drawShoe(shot.x,shot.y,shoeColor(shot.color),R);drawLauncher();requestAnimationFrame(draw)}
  function drawFalling(){fallingPieces.forEach(piece=>{piece.vy+=.42;piece.y+=piece.vy;piece.rotation+=piece.spin;ctx.save();ctx.globalAlpha=Math.max(0,1-(piece.y-canvas.height*.72)/(canvas.height*.35));ctx.translate(piece.x,piece.y);ctx.rotate(piece.rotation);drawShoe(0,0,shoeColor(piece.color),R);ctx.restore()});fallingPieces=fallingPieces.filter(piece=>piece.y<canvas.height+R*3)}
  function shoeColor(code){return code===-1?'#f8f4ff':code===-2?'#8a6840':colors[code]}
  function drawRope(){ctx.save();ctx.strokeStyle='#d7b47288';ctx.lineWidth=5;ctx.setLineDash([13,9]);ctx.beginPath();ctx.moveTo(0,42);ctx.lineTo(canvas.width,42);ctx.stroke();ctx.restore()}
  function drawShoe(x,y,color,r){ctx.save();ctx.translate(x,y);ctx.lineCap='round';ctx.shadowColor='#100703dd';ctx.shadowBlur=8;ctx.shadowOffsetY=5;const metal=ctx.createLinearGradient(-r,-r,r,r);metal.addColorStop(0,'#fff2b7');metal.addColorStop(.17,'#cf9239');metal.addColorStop(.48,'#4b250d');metal.addColorStop(.72,'#e2ae52');metal.addColorStop(1,'#623112');ctx.strokeStyle='#190b04';ctx.lineWidth=r*.88;ctx.beginPath();ctx.arc(0,0,r*.66,.08*Math.PI,.92*Math.PI,true);ctx.stroke();ctx.strokeStyle=metal;ctx.lineWidth=r*.72;ctx.stroke();ctx.shadowColor='transparent';ctx.strokeStyle='#2d1609';ctx.lineWidth=r*.48;ctx.stroke();ctx.strokeStyle=color;ctx.lineWidth=r*.36;ctx.stroke();ctx.strokeStyle='#fff0b499';ctx.lineWidth=r*.075;ctx.beginPath();ctx.arc(-1,-2,r*.57,.13*Math.PI,.73*Math.PI,true);ctx.stroke();for(const a of [.12,.31,.69,.88]){const q=a*Math.PI,px=Math.cos(q)*r*.66,py=Math.sin(q)*r*.66;ctx.fillStyle='#160a04';ctx.beginPath();ctx.arc(px,py,4.2,0,7);ctx.fill();ctx.fillStyle='#f4ca73';ctx.beginPath();ctx.arc(px-1,py-1,2,0,7);ctx.fill()}ctx.restore()}
  function drawLauncher(){const x=canvas.width/2,y=canvas.height-65,code=selectedPower==='rainbow'?-1:selectedPower==='hammer'?-2:nextColor;ctx.save();ctx.shadowColor='#120803cc';ctx.shadowBlur=14;ctx.shadowOffsetY=8;const wood=ctx.createRadialGradient(x-12,y-16,5,x,y,57);wood.addColorStop(0,'#8a5224');wood.addColorStop(.55,'#44230e');wood.addColorStop(1,'#1d0d05');ctx.fillStyle=wood;ctx.beginPath();ctx.arc(x,y,54,0,7);ctx.fill();ctx.shadowColor='transparent';ctx.strokeStyle='#2a1207';ctx.lineWidth=10;ctx.stroke();ctx.strokeStyle='#d19a3f';ctx.lineWidth=5;ctx.stroke();ctx.strokeStyle='#f1ca70';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(x,y,43,0,7);ctx.stroke();ctx.fillStyle='#241208';ctx.beginPath();ctx.arc(x,y,35,0,7);ctx.fill();drawShoe(x,y,shoeColor(code),27);ctx.fillStyle='#e8bb60';ctx.font='700 9px Montserrat';ctx.textAlign='center';ctx.fillText(selectedPower?'POWER SHOE':'NEXT SHOE',x,y-58);ctx.restore()}
  function drawGuide(){const x=canvas.width/2,y=canvas.height-65,dx=aim.x-x,dy=Math.min(-40,aim.y-y),len=Math.hypot(dx,dy),ux=dx/len,uy=dy/len;ctx.save();ctx.strokeStyle='#fff8dbaa';ctx.lineWidth=3;ctx.setLineDash([9,10]);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+ux*250,y+uy*250);ctx.stroke();ctx.restore()}
  function pointer(e){const rect=canvas.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:(p.clientX-rect.left)*canvas.width/rect.width,y:(p.clientY-rect.top)*canvas.height/rect.height}}
  function aimAt(e){if(!active||shot)return;aim=pointer(e)}
  function fire(e){if(!active||shot)return;e.preventDefault();aimAt(e);const x=canvas.width/2,y=canvas.height-65,dx=aim.x-x,dy=Math.min(-50,aim.y-y),len=Math.hypot(dx,dy),power=selectedPower;shot={x,y,vx:dx/len*14,vy:dy/len*14,color:power==='rainbow'?-1:power==='hammer'?-2:nextColor};if(power){powers[power]--;selectedPower=null}else nextColor=randomBoardColor();updateUI();tone(440,.05);tick()}
  function tick(){if(!shot)return;shot.x+=shot.vx;shot.y+=shot.vy;if(shot.x<R||shot.x>canvas.width-R){shot.vx*=-1;shot.x=Math.max(R,Math.min(canvas.width-R,shot.x));tone(240,.025)}let hit=shot.y<TOP;for(let r=0;!hit&&r<board.length;r++)for(let c=0;c<(board[r]?.length||0);c++)if(board[r][c]!=null){const p=pos(r,c);if(Math.hypot(shot.x-p.x,shot.y-p.y)<R*1.82){hit=true;break}}if(hit){land()}else requestAnimationFrame(tick)}
  function land(){const cell=cellFrom(shot.x,shot.y);while(board.length<=cell.r)board.push(Array(COLS-(board.length%2)).fill(null));while(board[cell.r].length<COLS-(cell.r%2))board[cell.r].push(null);let c=cell.c;if(shot.color===-2){const smashed=[[cell.r,c],...neighbors(cell.r,c)];let removed=0;smashed.forEach(([r,k])=>{if(board[r]?.[k]!=null){board[r][k]=null;removed++}});shot=null;combo++;score+=removed*45;coins+=Math.max(1,Math.floor(removed/2));showPrize(`Ranch Hammer! ${removed} horseshoes cleared`);afterLand(true);return}if(board[cell.r][c]!=null){const tries=[[cell.r+1,c],[cell.r+1,c-1],[cell.r,c+1],[cell.r,c-1]].filter(([r,k])=>r>=0&&k>=0);const open=tries.find(([r,k])=>board[r]?.[k]==null);if(open){cell.r=open[0];c=open[1];while(board.length<=cell.r)board.push(Array(COLS-(cell.r%2)).fill(null))}}if(shot.color===-1){const touching=neighbors(cell.r,c).map(([r,k])=>board[r]?.[k]).filter(Number.isInteger);shot.color=touching[0]??randomBoardColor();showPrize('Rainbow Shoe matched the trail!')}board[cell.r][c]=shot.color;const matched=flood(cell.r,c,shot.color);shot=null;if(matched.length>=3){matched.forEach(([r,k])=>board[r][k]=null);const dropped=dropLoose();combo++;const multiplier=1+Math.floor(combo/3),gain=(matched.length*20+dropped*35)*multiplier;score+=gain;coins+=Math.max(1,Math.floor(gain/100));if(combo%3===0){coins+=5;shots++;powers[Math.random()<.5?'rainbow':'hammer']++;showPrize(`Combo Prize! ×${multiplier} • +5 coins • +1 shot`)}tone(660,.08);setTimeout(()=>tone(880,.12),90);afterLand(true)}else{combo=0;shots--;tone(180,.12);afterLand(false)}}
  function afterLand(success){trim();updateUI();if(board.flat().filter(Number.isInteger).length===0)finish(true);else if(shots<=0||board.length*ROW_H+TOP>canvas.height-180)finish(false)}
  function showPrize(message){ui.prizeMessage.textContent=message;ui.toast.classList.remove('show');void ui.toast.offsetWidth;ui.toast.classList.add('show')}
  function neighbors(r,c){const d=r%2?[[0,-1],[0,1],[-1,0],[-1,1],[1,0],[1,1]]:[[0,-1],[0,1],[-1,-1],[-1,0],[1,-1],[1,0]];return d.map(([a,b])=>[r+a,c+b]).filter(([a,b])=>a>=0&&b>=0&&b<(COLS-(a%2)))}
  function flood(r,c,color){const out=[],seen=new Set(),q=[[r,c]];while(q.length){const p=q.pop(),key=p.join(':');if(seen.has(key)||board[p[0]]?.[p[1]]!==color)continue;seen.add(key);out.push(p);q.push(...neighbors(...p))}return out}
  function dropLoose(){const keep=new Set(),q=[];(board[0]||[]).forEach((v,c)=>{if(v!=null)q.push([0,c])});while(q.length){const p=q.pop(),key=p.join(':');if(keep.has(key)||board[p[0]]?.[p[1]]==null)continue;keep.add(key);q.push(...neighbors(...p))}let n=0;for(let r=0;r<board.length;r++)for(let c=0;c<board[r].length;c++)if(board[r][c]!=null&&!keep.has(r+':'+c)){const p=pos(r,c);fallingPieces.push({x:p.x,y:p.y,color:board[r][c],vy:2+Math.random()*2,rotation:0,spin:(Math.random()-.5)*.12});board[r][c]=null;n++}if(n)showPrize(`${n} unsupported horseshoe${n===1?'':'s'} fell! Bonus points awarded.`);return n}
  function trim(){while(board.length&&board[board.length-1].every(v=>v==null))board.pop()}
  function updateUI(){ui.level.textContent=level;ui.score.textContent=score.toLocaleString();ui.coins.textContent=coins;ui.combo.textContent=`×${1+Math.floor(combo/3)}`;ui.shots.textContent=shots;ui.rainbow.textContent=powers.rainbow;ui.hammer.textContent=powers.hammer;['rainbow','hammer'].forEach(name=>{const button=byId(name+'Power');button.disabled=!powers[name]||!active;button.classList.toggle('selected',selectedPower===name)})}
  function finish(win){active=false;byId('resultEyebrow').textContent=win?'Mission Complete':'Trail Paused';byId('resultTitle').textContent=win?'Heritage Trail Restored!':'Give It Another Ride';byId('resultText').textContent=win?`You cleared level ${level} and helped carry the story forward. ${coins} Conservation Coins earned so far.`:'Match groups of three before the horseshoes reach the rider. Your score and coins are safe.';byId('nextBtn').textContent=win?'Ride to Next Level':'Try This Level Again';ui.fact.textContent=facts[(level)%facts.length];ui.result.classList.add('open');ui.result.dataset.win=win?'1':'0'}
  function tone(freq,duration){if(!sound)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const ac=tone.ac||(tone.ac=new A()),o=ac.createOscillator(),g=ac.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.04,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+duration);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+duration)}
  function choosePower(name){if(!active||shot||!powers[name])return;selectedPower=selectedPower===name?null:name;updateUI();showPrize(selectedPower?`${name==='rainbow'?'Rainbow Shoe':'Ranch Hammer'} ready — aim and fire`:'Power-up returned')}
  byId('startBtn').onclick=()=>{ui.start.classList.remove('open');setup();active=true;updateUI()};byId('nextBtn').onclick=()=>{if(ui.result.dataset.win==='1')level++;ui.result.classList.remove('open');setup();active=true;updateUI()};byId('soundBtn').onclick=()=>{sound=!sound;byId('soundBtn').textContent=sound?'♪':'×'};byId('rainbowPower').onclick=()=>choosePower('rainbow');byId('hammerPower').onclick=()=>choosePower('hammer');
  canvas.addEventListener('mousemove',aimAt);canvas.addEventListener('touchmove',aimAt,{passive:true});canvas.addEventListener('click',fire);canvas.addEventListener('touchend',e=>{if(active&&!shot){const t=e.changedTouches[0],rect=canvas.getBoundingClientRect();aim={x:(t.clientX-rect.left)*canvas.width/rect.width,y:(t.clientY-rect.top)*canvas.height/rect.height};fire({preventDefault(){},clientX:t.clientX,clientY:t.clientY})}},{passive:false});
  setup();draw();
})();
