(() => {
  'use strict';
  const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d');
  const ui={level:byId('levelLabel'),score:byId('scoreLabel'),coins:byId('coinLabel'),combo:byId('comboLabel'),shots:byId('shotsLabel'),fact:byId('factText'),start:byId('startPanel'),result:byId('resultPanel'),toast:byId('prizeToast'),prizeMessage:byId('prizeMessage'),rainbow:byId('rainbowCount'),hammer:byId('hammerCount'),chapter:byId('chapterLabel'),mission:byId('missionLabel'),starFill:byId('starFill'),starLabel:byId('starLabel'),resultStars:byId('resultStars'),achievements:byId('achievementPanel'),achievementList:byId('achievementList'),trailMap:byId('trailMapPanel'),trailStops:byId('trailStops')};
  const colors=['#b66a36','#d7a93d','#3d91b6','#df7b30','#c84d3f','#87a83e','#446fb8'];
  const tileSources=['feed-sack','hay-bale','water-bucket','carrot','apple','grain-bundle','ribbon-award'];
  const tileNames=['Feed Sack','Hay Bale','Water Bucket','Carrot','Apple','Grain Bundle','Ribbon Award'];
  const tileImages=tileSources.map(name=>{const image=new Image();image.src=`assets/bubbles/${name}.png`;return image});
  const launcherImage=new Image();launcherImage.src='assets/launcher-horseshoe.png';
  const facts=[
    'The Pure Puerto Rican Paso Fino is treasured for its naturally smooth, four-beat gait.',
    'The breed developed on Puerto Rico over centuries and is part of the island’s living heritage.',
    'Careful pedigrees help conservation breeders protect rare maternal and paternal lines.',
    'Preserving a breed also preserves the stories, skills, farms, and communities built around it.',
    'DNA parent verification helps safeguard the identity of a closed, historic horse population.',
    'Every healthy foal can represent an important link between generations of Puerto Rican horses.'
  ];
  const chapters=['Hacienda Beginnings','Mountain Pastures','Coastal Ranches','Coffee Country','Heritage Festival','Island Breeders','Conservation Reserve','Bloodline Keepers','Champions’ Passage','Legacy Summit'];
  const trailStories=[
    ['Meet the Puerto Rican Paso Fino','Begin with the breed’s signature: a naturally even, four-beat gait prized for a smooth ride. Each stop introduces the horses and people protecting this island legacy.'],
    ['Built for Island Terrain','Puerto Rico’s hills reward balance, careful foot placement, and stamina. Discover how terrain, daily work, and thoughtful horsemanship shaped the breed.'],
    ['From Mountains to Coast','Follow the trail across changing island landscapes and learn how horses connected farms, families, and communities.'],
    ['Horses of Coffee Country','Explore the working partnership between riders and horses on steep agricultural land, where a smooth gait and sure footing mattered.'],
    ['A Living Cultural Tradition','Paso Fino exhibitions celebrate rhythm, responsiveness, skilled training, and the bond between horse and rider.'],
    ['Families, Farms, and Breeders','Meet the caretakers who record pedigrees, raise healthy foals, and pass practical knowledge from one generation to the next.'],
    ['Why Conservation Matters','A small historic population needs careful stewardship. Responsible breeding protects health, diversity, identity, and a future for the breed.'],
    ['Following the Bloodlines','Pedigrees and parentage records help breeders make informed matches while preserving rare maternal and paternal lines.'],
    ['The Championship Passage','Test everything you have learned in advanced trail challenges inspired by precision, patience, and partnership.'],
    ['Carry the Legacy Forward','The final trail is about stewardship: healthy horses, accurate records, educated owners, and communities committed to the breed’s future.']
  ];
  const achievementDefs=[['first_ride','First Ride','Complete your first level'],['star_student','Star Student','Earn 15 stars'],['trail_master','Trail Master','Complete 10 levels'],['combo_caballero','Combo Caballero','Reach a ×3 multiplier'],['gravity_rider','Gravity Rider','Drop 25 loose horseshoes'],['coin_keeper','Conservation Keeper','Earn 100 coins'],['power_legacy','Power of the Legacy','Use 10 power-ups'],['ppr_champion','PPR Champion','Complete all 100 levels']];
  const saved=loadProgress();
  const R=34,GAP=4,COLS=9,ROW_H=R*1.76,TOP=76; let board=[],fallingPieces=[],level=saved.level,score=saved.score,coins=saved.coins,stars=saved.stars,completed=saved.completed,stats=saved.stats,earned=new Set(saved.earned),combo=0,levelScore=0,levelDropped=0,shots=8,active=false,aim={x:360,y:500},shot=null,nextColor=0,previewColor=1,sound=true,selectedPower=null,powers=saved.powers,missesSinceDrop=0,boardYOffset=0,rowAnimating=false;
  function byId(id){return document.getElementById(id)}
  function loadProgress(){try{const p=JSON.parse(localStorage.getItem('horseShoePopProgress')||'{}');return{level:Math.min(100,Math.max(1,p.level||1)),score:p.score||0,coins:p.coins||0,stars:p.stars||0,completed:p.completed||{},earned:p.earned||[],powers:{rainbow:p.powers?.rainbow??2,hammer:p.powers?.hammer??2},stats:{drops:p.stats?.drops||0,powers:p.stats?.powers||0,maxCombo:p.stats?.maxCombo||0}}}catch{return{level:1,score:0,coins:0,stars:0,completed:{},earned:[],powers:{rainbow:2,hammer:2},stats:{drops:0,powers:0,maxCombo:0}}}}
  function saveProgress(){localStorage.setItem('horseShoePopProgress',JSON.stringify({level,score,coins,stars,completed,earned:[...earned],powers,stats}))}
  function levelConfig(){const chapter=Math.min(9,Math.floor((level-1)/10)),step=(level-1)%10,boss=step===9;return{chapter,step,boss,type:boss?4:step%5,goal:(650+level*125)*(boss?1.45:1),dropGoal:4+Math.floor(level/6)+(boss?5:0),comboGoal:2+Math.floor(level/18)+(boss?1:0),rows:boss?8:Math.min(4+Math.floor(level/12),7),palette:Math.min(3+Math.floor((level-1)/7),7),shots:boss?Math.max(5,9-Math.floor(level/20)):Math.max(6,12-Math.floor(level/14)),fill:boss?.98:Math.min(.95,.82+level*.0015),rowDropEvery:level<4?0:boss?3:level<25?5:level<60?4:3}}
  function setup(){board=[];fallingPieces=[];combo=0;levelScore=0;levelDropped=0;missesSinceDrop=0;boardYOffset=0;rowAnimating=false;selectedPower=null;const cfg=levelConfig();for(let r=0;r<cfg.rows;r++){board[r]=[];for(let c=0;c<COLS-(r%2);c++){board[r][c]=Math.random()<cfg.fill?Math.floor(Math.random()*cfg.palette):null}}shots=cfg.shots;nextColor=randomBoardColor();previewColor=randomBoardColor();shot=null;updateUI()}
  function randomBoardColor(){const present=[...new Set(board.flat().filter(Number.isInteger))];return present.length?present[Math.floor(Math.random()*present.length)]:Math.floor(Math.random()*colors.length)}
  function pos(r,c){return{x:R+GAP+c*(R*2+GAP)+(r%2)*(R+GAP/2),y:TOP+r*ROW_H+boardYOffset}}
  function cellFrom(x,y){const r=Math.max(0,Math.round((y-TOP)/ROW_H)),offset=(r%2)*(R+GAP/2),c=Math.max(0,Math.min(COLS-1-(r%2),Math.round((x-R-GAP-offset)/(R*2+GAP))));return{r,c}}
  function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);drawRope();for(let r=0;r<board.length;r++)for(let c=0;c<(board[r]?.length||0);c++)if(board[r][c]!=null){const p=pos(r,c);drawBubble(p.x,p.y,board[r][c],R)}drawFalling();if(active&&!shot)drawGuide();if(shot)drawBubble(shot.x,shot.y,shot.color,R);drawLauncher();requestAnimationFrame(draw)}
  function drawFalling(){fallingPieces.forEach(piece=>{piece.vy+=.42;piece.y+=piece.vy;piece.rotation+=piece.spin;ctx.save();ctx.globalAlpha=Math.max(0,1-(piece.y-canvas.height*.72)/(canvas.height*.35));ctx.translate(piece.x,piece.y);ctx.rotate(piece.rotation);drawBubble(0,0,piece.color,R);ctx.restore()});fallingPieces=fallingPieces.filter(piece=>piece.y<canvas.height+R*3)}
  function shoeColor(code){return code===-1?'#f8f4ff':code===-2?'#8a6840':colors[code]}
  function drawRope(){ctx.save();ctx.strokeStyle='#d7b47288';ctx.lineWidth=5;ctx.setLineDash([13,9]);ctx.beginPath();ctx.moveTo(0,42);ctx.lineTo(canvas.width,42);ctx.stroke();ctx.restore()}
  function drawBubble(x,y,code,r){const icon=tileImages[code];ctx.save();ctx.translate(x,y);ctx.shadowColor='#100703cc';ctx.shadowBlur=8;ctx.shadowOffsetY=5;if(icon?.complete&&icon.naturalWidth){ctx.beginPath();ctx.arc(0,0,r*.93,0,Math.PI*2);ctx.clip();ctx.drawImage(icon,-r,-r,r*2,r*2)}else{const glass=ctx.createRadialGradient(-r*.28,-r*.32,2,0,0,r);glass.addColorStop(0,'#fffdf4');glass.addColorStop(.2,shoeColor(code));glass.addColorStop(1,'#241208');ctx.fillStyle=glass;ctx.beginPath();ctx.arc(0,0,r*.88,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#f2cf8d';ctx.lineWidth=2;ctx.stroke()}ctx.restore()}
  function drawShoe(x,y,color,r,icon){ctx.save();ctx.translate(x,y);ctx.lineCap='round';ctx.shadowColor='#100703cc';ctx.shadowBlur=7;ctx.shadowOffsetY=4;const bubble=ctx.createRadialGradient(-r*.15,-r*.18,2,0,0,r*.54);bubble.addColorStop(0,'#fff7d9');bubble.addColorStop(.28,color);bubble.addColorStop(1,'#241208');const metal=ctx.createLinearGradient(-r,-r,r,r);metal.addColorStop(0,'#fff2b7');metal.addColorStop(.17,'#cf9239');metal.addColorStop(.48,'#4b250d');metal.addColorStop(.72,'#e2ae52');metal.addColorStop(1,'#623112');ctx.strokeStyle='#190b04';ctx.lineWidth=r*.88;ctx.beginPath();ctx.arc(0,0,r*.68,.08*Math.PI,.92*Math.PI,true);ctx.stroke();ctx.strokeStyle=metal;ctx.lineWidth=r*.72;ctx.stroke();ctx.shadowColor='transparent';ctx.strokeStyle='#2d1609';ctx.lineWidth=r*.48;ctx.stroke();ctx.strokeStyle='#f0c568';ctx.lineWidth=r*.1;ctx.stroke();ctx.shadowColor='#100703aa';ctx.shadowBlur=4;ctx.fillStyle=bubble;ctx.beginPath();ctx.arc(0,0,r*.4,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#f4d98f';ctx.lineWidth=1.5;ctx.stroke();ctx.shadowColor='transparent';if(icon?.complete){ctx.save();ctx.beginPath();ctx.arc(0,0,r*.34,0,Math.PI*2);ctx.clip();ctx.drawImage(icon,-r*.37,-r*.37,r*.74,r*.74);ctx.restore();ctx.fillStyle='#fff8db44';ctx.beginPath();ctx.ellipse(-r*.1,-r*.15,r*.16,r*.07,-.4,0,Math.PI*2);ctx.fill()}for(const a of [.12,.31,.69,.88]){const q=a*Math.PI,px=Math.cos(q)*r*.68,py=Math.sin(q)*r*.68;ctx.fillStyle='#160a04';ctx.beginPath();ctx.arc(px,py,4.1,0,7);ctx.fill();ctx.fillStyle='#f4ca73';ctx.beginPath();ctx.arc(px-1,py-1,1.9,0,7);ctx.fill()}ctx.restore()}
  function drawLauncher(){const x=canvas.width/2,y=canvas.height-70,code=selectedPower==='rainbow'?-1:selectedPower==='hammer'?-2:nextColor;ctx.save();ctx.shadowColor='#0b0502dd';ctx.shadowBlur=18;ctx.shadowOffsetY=9;if(launcherImage.complete&&launcherImage.naturalWidth)ctx.drawImage(launcherImage,x-92,y-108,184,200);ctx.shadowColor='transparent';drawBubble(x,y,code,27);ctx.fillStyle='#f2c667';ctx.font='700 9px Montserrat';ctx.textAlign='center';ctx.fillText(selectedPower?'POWER SHOE':'CURRENT',x,y-102);ctx.strokeStyle='#7a4b22';ctx.lineWidth=8;ctx.beginPath();ctx.arc(x+103,y+11,35,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#e1b45b';ctx.lineWidth=3;ctx.stroke();drawBubble(x+103,y+11,previewColor,25);ctx.fillStyle='#f2c667';ctx.fillText('NEXT',x+103,y-34);ctx.restore()}
  function drawGuide(){const x=canvas.width/2,y=canvas.height-94,dx=aim.x-x,dy=Math.min(-40,aim.y-y),len=Math.hypot(dx,dy);let ux=dx/len,uy=dy/len,px=x,py=y,remaining=620;ctx.save();ctx.shadowColor='#ffc447';ctx.shadowBlur=7;ctx.strokeStyle='#ffe49ddd';ctx.lineWidth=3.5;ctx.setLineDash([7,11]);ctx.beginPath();ctx.moveTo(px,py);for(let bounce=0;bounce<3&&remaining>0;bounce++){const wallX=ux>0?canvas.width-R:R,wallT=Math.abs(ux)>.001?(wallX-px)/ux:Infinity,topT=uy<0?(TOP-py)/uy:Infinity,nextT=Math.min(remaining,wallT>0?wallT:Infinity,topT>0?topT:Infinity);px+=ux*nextT;py+=uy*nextT;ctx.lineTo(px,py);remaining-=nextT;if(nextT===topT||remaining<=0)break;if(nextT===wallT){ux*=-1;px+=ux*.5}}ctx.stroke();ctx.restore()}
  function pointer(e){const rect=canvas.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:(p.clientX-rect.left)*canvas.width/rect.width,y:(p.clientY-rect.top)*canvas.height/rect.height}}
  function aimAt(e){if(!active||shot)return;aim=pointer(e)}
  function fire(e){if(!active||shot||rowAnimating)return;e.preventDefault();aimAt(e);const x=canvas.width/2,y=canvas.height-71,dx=aim.x-x,dy=Math.min(-50,aim.y-y),len=Math.hypot(dx,dy),power=selectedPower;shot={x,y,vx:dx/len*14,vy:dy/len*14,color:power==='rainbow'?-1:power==='hammer'?-2:nextColor};if(power){powers[power]--;stats.powers++;selectedPower=null}else{nextColor=previewColor;previewColor=randomBoardColor()}updateUI();soundCue('fire');tick()}
  function tick(){if(!shot)return;shot.x+=shot.vx;shot.y+=shot.vy;if(shot.x<R||shot.x>canvas.width-R){shot.vx*=-1;shot.x=Math.max(R,Math.min(canvas.width-R,shot.x));soundCue('bank')}let hit=shot.y<TOP,hitCell=null;for(let r=0;!hit&&r<board.length;r++)for(let c=0;c<(board[r]?.length||0);c++)if(board[r][c]!=null){const p=pos(r,c);if(Math.hypot(shot.x-p.x,shot.y-p.y)<R*1.82){hit=true;hitCell={r,c};break}}let target=null;if(hitCell){target=neighbors(hitCell.r,hitCell.c).filter(([r,c])=>board[r]?.[c]==null).sort((a,b)=>{const ap=pos(a[0],a[1]),bp=pos(b[0],b[1]);return Math.hypot(shot.x-ap.x,shot.y-ap.y)-Math.hypot(shot.x-bp.x,shot.y-bp.y)})[0]}if(hit)settleShot(target||Object.values(cellFrom(shot.x,shot.y)));else requestAnimationFrame(tick)}
  function settleShot(target){const startX=shot.x,startY=shot.y,p=pos(target[0],target[1]),began=performance.now(),duration=165;function step(now){if(!shot)return;const t=Math.min(1,(now-began)/duration),ease=1-Math.pow(1-t,3);shot.x=startX+(p.x-startX)*ease;shot.y=startY+(p.y-startY)*ease;if(t<1)requestAnimationFrame(step);else{soundCue('settle');land()}}requestAnimationFrame(step)}
  function addScore(gain){score+=gain;levelScore+=gain;coins+=Math.max(1,Math.floor(gain/100))}
  function land(){const cell=cellFrom(shot.x,shot.y);while(board.length<=cell.r)board.push(Array(COLS-(board.length%2)).fill(null));while(board[cell.r].length<COLS-(cell.r%2))board[cell.r].push(null);let c=cell.c;if(shot.color===-2){const smashed=[[cell.r,c],...neighbors(cell.r,c)];let removed=0;smashed.forEach(([r,k])=>{if(board[r]?.[k]!=null){board[r][k]=null;removed++}});shot=null;combo++;addScore(removed*45);showPrize(`Ranch Hammer! ${removed} horseshoes cleared`);soundCue('power');afterLand(true);return}if(board[cell.r][c]!=null){const tries=[[cell.r+1,c],[cell.r+1,c-1],[cell.r,c+1],[cell.r,c-1]].filter(([r,k])=>r>=0&&k>=0);const open=tries.find(([r,k])=>board[r]?.[k]==null);if(open){cell.r=open[0];c=open[1];while(board.length<=cell.r)board.push(Array(COLS-(cell.r%2)).fill(null))}}if(shot.color===-1){const touching=neighbors(cell.r,c).map(([r,k])=>board[r]?.[k]).filter(Number.isInteger);shot.color=touching[0]??randomBoardColor();showPrize('Rainbow Shoe matched the trail!')}board[cell.r][c]=shot.color;const matched=flood(cell.r,c,shot.color);shot=null;if(matched.length>=3){matched.forEach(([r,k])=>board[r][k]=null);const dropped=dropLoose();combo++;stats.maxCombo=Math.max(stats.maxCombo,combo);const multiplier=1+Math.floor(combo/3),gain=(matched.length*20+dropped*35)*multiplier;addScore(gain);if(combo%3===0){coins+=5;shots++;powers[Math.random()<.5?'rainbow':'hammer']++;showPrize(`Combo Prize! ×${multiplier} • +5 coins • +1 shot`);soundCue('prize')}else soundCue('match');afterLand(true)}else{combo=0;shots--;soundCue('miss');afterLand(false)}}
  function missionComplete(){const cfg=levelConfig(),empty=board.flat().filter(Number.isInteger).length===0;return empty||(cfg.type===1&&levelScore>=cfg.goal)||(cfg.type===2&&levelDropped>=cfg.dropGoal)||(cfg.type===3&&1+Math.floor(combo/3)>=cfg.comboGoal)||(cfg.type===4&&levelScore>=cfg.goal)}
  function afterLand(success){trim();updateUI();const cfg=levelConfig();if(!success&&cfg.rowDropEvery&&++missesSinceDrop>=cfg.rowDropEvery){missesSinceDrop=0;dropPressureRow(resolveAfterLand);return}resolveAfterLand()}
  function resolveAfterLand(){updateUI();if(missionComplete())finish(true);else if(shots<=0||board.length*ROW_H+TOP>canvas.height-180)finish(false)}
  function dropPressureRow(done){
    rowAnimating=true;
    const cfg=levelConfig(),fresh=Array.from({length:COLS},()=>Math.floor(Math.random()*cfg.palette)),shifted=[fresh];
    board.forEach((row,index)=>{const expected=COLS-((index+1)%2),copy=row.slice(0,expected);while(copy.length<expected)copy.push(null);shifted.push(copy)});
    board=shifted;boardYOffset=-ROW_H;showPrize('Trail pressure! A new horseshoe row is dropping in.');soundCue('row');
    const began=performance.now(),duration=340;function step(now){const t=Math.min(1,(now-began)/duration);boardYOffset=-ROW_H*(1-(1-Math.pow(1-t,3)));if(t<1)requestAnimationFrame(step);else{boardYOffset=0;rowAnimating=false;soundCue('thud');done()}}requestAnimationFrame(step)
  }
  function showPrize(message){ui.prizeMessage.textContent=message;ui.toast.classList.remove('show');void ui.toast.offsetWidth;ui.toast.classList.add('show')}
  function neighbors(r,c){const d=r%2?[[0,-1],[0,1],[-1,0],[-1,1],[1,0],[1,1]]:[[0,-1],[0,1],[-1,-1],[-1,0],[1,-1],[1,0]];return d.map(([a,b])=>[r+a,c+b]).filter(([a,b])=>a>=0&&b>=0&&b<(COLS-(a%2)))}
  function flood(r,c,color){const out=[],seen=new Set(),q=[[r,c]];while(q.length){const p=q.pop(),key=p.join(':');if(seen.has(key)||board[p[0]]?.[p[1]]!==color)continue;seen.add(key);out.push(p);q.push(...neighbors(...p))}return out}
  function dropLoose(){const keep=new Set(),q=[];(board[0]||[]).forEach((v,c)=>{if(v!=null)q.push([0,c])});while(q.length){const p=q.pop(),key=p.join(':');if(keep.has(key)||board[p[0]]?.[p[1]]==null)continue;keep.add(key);q.push(...neighbors(...p))}let n=0;for(let r=0;r<board.length;r++)for(let c=0;c<board[r].length;c++)if(board[r][c]!=null&&!keep.has(r+':'+c)){const p=pos(r,c);fallingPieces.push({x:p.x,y:p.y,color:board[r][c],vy:2+Math.random()*2,rotation:0,spin:(Math.random()-.5)*.12});board[r][c]=null;n++}if(n){levelDropped+=n;stats.drops+=n;showPrize(`${n} unsupported horseshoe${n===1?'':'s'} fell! Bonus points awarded.`);soundCue('fall')}return n}
  function trim(){while(board.length&&board[board.length-1].every(v=>v==null))board.pop()}
  function missionText(cfg=levelConfig()){const goal=cfg.type===0?'Clear every bubble':cfg.type===1?`Earn ${Math.round(cfg.goal).toLocaleString()} points`:cfg.type===2?`Drop ${cfg.dropGoal} loose bubbles`:cfg.type===3?`Reach a ×${cfg.comboGoal} combo`:`Fill the feed wagon • ${Math.round(cfg.goal).toLocaleString()} points`;return cfg.boss?`CHAMPIONSHIP • ${goal}`:goal}
  function challengeReward(cfg=levelConfig()){return cfg.boss?'Championship reward: 3 stars + bonus Conservation Coins':'Reward: up to 3 Heritage Stars'}
  function renderTrailMap(required=false){
    const cfg=levelConfig(),chapterStart=cfg.chapter*10+1,story=trailStories[cfg.chapter];
    byId('trailMapTitle').textContent=chapters[cfg.chapter];
    byId('trailMapProgress').textContent=`Chapter ${cfg.chapter+1} of 10 • Level ${level} of 100`;
    byId('trailStoryLabel').textContent=cfg.boss?'Championship heritage lesson':'Heritage lesson';
    byId('trailStoryTitle').textContent=story[0];
    byId('trailStoryText').textContent=story[1];
    byId('trailChallengeLabel').textContent=cfg.boss?'Super-hard championship challenge':'Next challenge';
    byId('trailChallengeText').textContent=missionText(cfg);
    const justUnlocked=(level-1)%7===0&&cfg.palette>3?` • New bubble topic: ${tileNames[cfg.palette-1]}`:'';
    const pressure=cfg.rowDropEvery?` • New row after ${cfg.rowDropEvery} missed shots`:'';
    byId('trailChallengeReward').textContent=challengeReward(cfg)+justUnlocked+pressure;
    byId('rideTrailBtn').textContent=level===100&&completed[100]?'Ride Level 100 Again':`Ride to Level ${level}`;
    byId('closeTrailMap').hidden=required;
    const highestCompleted=Math.max(0,...Object.keys(completed).map(Number));
    const unlocked=Math.min(100,Math.max(level,highestCompleted+1));
    ui.trailStops.innerHTML=Array.from({length:10},(_,i)=>{const n=chapterStart+i,isDone=Boolean(completed[n]),isCurrent=n===level,isLocked=n>unlocked;return `<button class="trail-stop ${isDone?'completed':''} ${isCurrent?'current':''} ${isLocked?'locked':''}" data-level="${n}" ${isLocked?'disabled':''} aria-label="Level ${n}${isDone?', completed':''}${isCurrent?', current':''}">${isDone?'★':n}</button>`}).join('');
    ui.trailStops.querySelectorAll('button:not(:disabled)').forEach(button=>button.onclick=()=>{level=Number(button.dataset.level);saveProgress();renderTrailMap(required);updateUI()});
  }
  function openTrailMap(required=false){
    ui.trailMap.dataset.resume=!required&&active?'1':'0';
    active=false;
    renderTrailMap(required);
    ui.trailMap.classList.add('open');
  }
  function closeTrailMap(resume=false){ui.trailMap.classList.remove('open');if(resume)active=true;updateUI()}
  function levelStars(){const cfg=levelConfig(),base=levelScore>=cfg.goal?1:0,skill=levelDropped>=cfg.dropGoal||stats.maxCombo>=cfg.comboGoal*3?1:0,finish=board.flat().filter(Number.isInteger).length===0?1:0;return Math.min(3,base+skill+finish)}
  function updateUI(){const cfg=levelConfig(),s=levelStars(),pressure=cfg.rowDropEvery?` • New row in ${cfg.rowDropEvery-missesSinceDrop} misses`:'';ui.level.textContent=`${level}/100`;ui.score.textContent=score.toLocaleString();ui.coins.textContent=coins;ui.combo.textContent=`×${1+Math.floor(combo/3)}`;ui.shots.textContent=shots;ui.rainbow.textContent=powers.rainbow;ui.hammer.textContent=powers.hammer;ui.chapter.textContent=`Chapter ${cfg.chapter+1} • ${chapters[cfg.chapter]}`;ui.mission.textContent=missionText(cfg)+pressure;ui.starFill.style.width=`${Math.min(100,levelScore/cfg.goal*100)}%`;ui.starLabel.textContent=`${s} / 3 stars`;['rainbow','hammer'].forEach(name=>{const button=byId(name+'Power');button.disabled=!powers[name]||!active||rowAnimating;button.classList.toggle('selected',selectedPower===name)})}
  function checkAchievements(){const tests={first_ride:Object.keys(completed).length>=1,star_student:stars>=15,trail_master:Object.keys(completed).length>=10,combo_caballero:stats.maxCombo>=6,gravity_rider:stats.drops>=25,coin_keeper:coins>=100,power_legacy:stats.powers>=10,ppr_champion:Object.keys(completed).length>=100};achievementDefs.forEach(([id,name])=>{if(tests[id]&&!earned.has(id)){earned.add(id);coins+=10;showPrize(`Achievement unlocked: ${name} • +10 coins`)}})}
  function finish(win){active=false;let earnedStars=0;if(win){earnedStars=Math.max(1,levelStars());const old=completed[level]||0;completed[level]=Math.max(old,earnedStars);stars+=Math.max(0,earnedStars-old);coins+=earnedStars*3;checkAchievements();saveProgress();soundCue('win')}byId('resultEyebrow').textContent=win?'Mission Complete':'Trail Paused';byId('resultTitle').textContent=win?(level===100?'PPR Legacy Champion!':level%10===0?'Championship Trail Conquered!':'Heritage Trail Restored!'):'Give It Another Ride';byId('resultText').textContent=win?`Level ${level} complete • ${earnedStars*3} prize coins earned. You now have ${stars} heritage stars.`:'Match groups of three before the bubbles reach the rider. Your score and coins are safe.';ui.resultStars.textContent=win?'★'.repeat(earnedStars)+'☆'.repeat(3-earnedStars):'☆☆☆';byId('nextBtn').textContent=win?'View Heritage Map':'Try This Level Again';ui.fact.textContent=facts[(level)%facts.length];ui.result.classList.add('open');ui.result.dataset.win=win?'1':'0'}
  function tone(freq,duration,type='sine',gain=.04,delay=0){if(!sound)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const ac=tone.ac||(tone.ac=new A()),o=ac.createOscillator(),g=ac.createGain(),start=ac.currentTime+delay;o.frequency.value=freq;o.type=type;g.gain.setValueAtTime(gain,start);g.gain.exponentialRampToValueAtTime(.001,start+duration);o.connect(g).connect(ac.destination);o.start(start);o.stop(start+duration)}
  function soundCue(name){const cues={fire:[[430,.05,'triangle',.035,0],[610,.06,'sine',.025,.035]],bank:[[235,.035,'square',.018,0]],settle:[[310,.045,'triangle',.025,0]],match:[[620,.08,'sine',.04,0],[820,.11,'sine',.04,.075]],miss:[[170,.12,'triangle',.035,0]],fall:[[360,.08,'triangle',.03,0],[260,.1,'triangle',.03,.07],[170,.13,'triangle',.03,.15]],power:[[190,.08,'square',.03,0],[440,.15,'triangle',.04,.08]],prize:[[520,.08,'sine',.04,0],[660,.08,'sine',.04,.09],[880,.16,'sine',.04,.18]],row:[[330,.08,'triangle',.03,0],[260,.08,'triangle',.03,.1],[210,.12,'triangle',.04,.2]],thud:[[105,.18,'square',.045,0]],win:[[520,.1,'sine',.04,0],[660,.1,'sine',.04,.1],[880,.2,'sine',.045,.2]],start:[[330,.08,'sine',.03,0],[495,.12,'sine',.035,.08]]};(cues[name]||[]).forEach(args=>tone(...args))}
  function choosePower(name){if(!active||shot||!powers[name])return;selectedPower=selectedPower===name?null:name;updateUI();showPrize(selectedPower?`${name==='rainbow'?'Rainbow Shoe':'Ranch Hammer'} ready — aim and fire`:'Power-up returned')}
  function renderAchievements(){ui.achievementList.innerHTML=achievementDefs.map(([id,name,desc])=>`<article class="achievement ${earned.has(id)?'earned':''}"><span>${earned.has(id)?'★':'☆'}</span><div><b>${name}</b><small>${desc}</small></div><em>${earned.has(id)?'Earned':'+10 coins'}</em></article>`).join('')}
  byId('startBtn').onclick=()=>{ui.start.classList.remove('open');setup();active=true;updateUI();soundCue('start')};
  byId('nextBtn').onclick=()=>{const won=ui.result.dataset.win==='1';ui.result.classList.remove('open');if(won){if(level<100)level++;saveProgress();openTrailMap(true)}else{setup();active=true;updateUI()}};
  byId('rideTrailBtn').onclick=()=>{ui.start.classList.remove('open');closeTrailMap(false);setup();active=true;updateUI();soundCue('start')};
  byId('trailBtn').onclick=()=>openTrailMap(false);
  byId('closeTrailMap').onclick=()=>closeTrailMap(ui.trailMap.dataset.resume==='1');
  byId('soundBtn').onclick=()=>{sound=!sound;byId('soundBtn').textContent=sound?'♪':'×'};byId('rainbowPower').onclick=()=>choosePower('rainbow');byId('hammerPower').onclick=()=>choosePower('hammer');byId('achievementBtn').onclick=()=>{renderAchievements();ui.achievements.classList.add('open')};byId('closeAchievements').onclick=()=>ui.achievements.classList.remove('open');
  canvas.addEventListener('mousemove',aimAt);canvas.addEventListener('touchmove',aimAt,{passive:true});canvas.addEventListener('click',fire);canvas.addEventListener('touchend',e=>{if(active&&!shot){const t=e.changedTouches[0],rect=canvas.getBoundingClientRect();aim={x:(t.clientX-rect.left)*canvas.width/rect.width,y:(t.clientY-rect.top)*canvas.height/rect.height};fire({preventDefault(){},clientX:t.clientX,clientY:t.clientY})}},{passive:false});
  setup();draw();
})();
